name: noctus_mobile
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: 9.0.0
  collection: 1.19.1
  dio: 5.8.0+1
  flutter_bloc: 9.0.0
  flutter_dotenv: 5.2.1
  font_awesome_flutter: 10.8.0
  get_it: 8.0.3
  intl: ^0.20.2
  shared_preferences: 2.5.2
  sqflite: 2.4.2
  image_picker: ^1.0.7
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0
  mockito: 5.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/aplication/